/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var Analizador = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,15],$V1=[1,14],$V2=[1,10],$V3=[1,11],$V4=[1,12],$V5=[1,13],$V6=[5,13,16,21,24,26,39],$V7=[1,19],$V8=[1,20],$V9=[1,32],$Va=[1,33],$Vb=[23,25,28,35,37,70,71],$Vc=[1,39],$Vd=[41,42],$Ve=[1,84],$Vf=[1,93],$Vg=[1,100],$Vh=[55,56],$Vi=[65,66],$Vj=[1,108],$Vk=[32,58],$Vl=[60,61],$Vm=[63,68];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"S":3,"LIST_BLOCK":4,"EOF":5,"BLOCK":6,"MENSAJE":7,"DATA":8,"ERROR":9,"DBMS":10,"LOGOUT":11,"LOGIN":12,"res_loginOpen":13,"STATUS":14,"res_loginClose":15,"res_logoutOpen":16,"STATUS2":17,"res_logoutClose":18,"res_success":19,"res_fail":20,"res_messageOpen":21,"T1":22,"res_messageClose":23,"res_dataOpen":24,"res_dataClose":25,"res_errorOpen":26,"res_lexemaOpen":27,"res_lexemaClose":28,"res_lineOpen":29,"numero":30,"res_lineClose":31,"res_columnOpen":32,"res_columnClose":33,"res_typeOpen":34,"res_typeClose":35,"res_descripcionOpen":36,"res_descripcionClose":37,"res_errorClose":38,"res_dataBasesOpen":39,"DATA_BASES":40,"res_dataBasesClose":41,"res_dataBaseOpen":42,"CONTENIDO":43,"res_dataBaseClose":44,"res_nameOpen":45,"id":46,"res_nameClose":47,"res_tablesOpen":48,"TABLES":49,"res_typesOpen":50,"TYPES":51,"res_proceduresOpen":52,"PROCEDURES":53,"TABLE":54,"res_tablesClose":55,"res_tableOpen":56,"COLUMNAS":57,"res_tableClose":58,"TYPE":59,"res_typesClose":60,"res_typeCQLOpen":61,"ATRIBUTOS":62,"res_typeCQLClose":63,"PROCEDURE":64,"res_proceduresClose":65,"res_procedureOpen":66,"res_procedureClose":67,"res_atributtesOpen":68,"res_atributtesClose":69,"TODO":70,"WS":71,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",13:"res_loginOpen",15:"res_loginClose",16:"res_logoutOpen",18:"res_logoutClose",19:"res_success",20:"res_fail",21:"res_messageOpen",23:"res_messageClose",24:"res_dataOpen",25:"res_dataClose",26:"res_errorOpen",27:"res_lexemaOpen",28:"res_lexemaClose",29:"res_lineOpen",30:"numero",31:"res_lineClose",32:"res_columnOpen",33:"res_columnClose",34:"res_typeOpen",35:"res_typeClose",36:"res_descripcionOpen",37:"res_descripcionClose",38:"res_errorClose",39:"res_dataBasesOpen",41:"res_dataBasesClose",42:"res_dataBaseOpen",44:"res_dataBaseClose",45:"res_nameOpen",46:"id",47:"res_nameClose",48:"res_tablesOpen",50:"res_typesOpen",52:"res_proceduresOpen",55:"res_tablesClose",56:"res_tableOpen",58:"res_tableClose",60:"res_typesClose",61:"res_typeCQLOpen",63:"res_typeCQLClose",65:"res_proceduresClose",66:"res_procedureOpen",67:"res_procedureClose",68:"res_atributtesOpen",69:"res_atributtesClose",70:"TODO",71:"WS"},
productions_: [0,[3,2],[4,2],[4,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[12,3],[11,3],[17,1],[17,1],[14,1],[14,1],[7,3],[8,3],[9,17],[10,3],[40,4],[40,3],[43,9],[49,2],[49,1],[54,7],[54,6],[57,4],[57,3],[51,2],[51,1],[59,7],[59,6],[53,2],[53,1],[64,4],[64,3],[62,4],[62,3],[22,2],[22,2],[22,1],[22,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

	return ast;

break;
case 4:
ast.mensajes[ast.contMess++] = $$[$0];
break;
case 5:
ast.data[ast.contData++] = $$[$0];
break;
case 6:
ast.errores[ast.contErr++] = $$[$0];
break;
case 12:
ast.logout = true;
break;
case 13:
ast.logout = false;
break;
case 14:
ast.login = true;
break;
case 15:
ast.login = false;
break;
case 16:
this.$ = $$[$0-1];
break;
case 17:
this.$=$$[$0-1];
break;
case 18:
var error = new TokenError(); error.lexema = $$[$0-14]; error.fila = $$[$0-11]; error.columna=$$[$0-8]; 
			error.tipo = $$[$0-5]; error.descripcion = $$[$0-2];
			this.$ = error;
break;
case 20:

	var data_base = {};
	data_base.
	ast.dbms[ast.contDBMS++] = $$[$0-3];

break;
case 39: case 40:
this.$ = $$[$0-1]+$$[$0];
break;
case 41: case 42:
this.$=$$[$0];
break;
}
},
table: [{3:1,4:2,6:3,7:4,8:5,9:6,10:7,11:8,12:9,13:$V0,16:$V1,21:$V2,24:$V3,26:$V4,39:$V5},{1:[3]},{5:[1,16],6:17,7:4,8:5,9:6,10:7,11:8,12:9,13:$V0,16:$V1,21:$V2,24:$V3,26:$V4,39:$V5},o($V6,[2,3]),o($V6,[2,4]),o($V6,[2,5]),o($V6,[2,6]),o($V6,[2,7]),o($V6,[2,8]),o($V6,[2,9]),{22:18,70:$V7,71:$V8},{22:21,70:$V7,71:$V8},{27:[1,22]},{40:23,42:[1,24]},{17:25,19:[1,26],20:[1,27]},{14:28,19:[1,29],20:[1,30]},{1:[2,1]},o($V6,[2,2]),{23:[1,31],70:$V9,71:$Va},o($Vb,[2,41]),o($Vb,[2,42]),{25:[1,34],70:$V9,71:$Va},{22:35,70:$V7,71:$V8},{41:[1,36],42:[1,37]},{43:38,45:$Vc},{18:[1,40]},{18:[2,12]},{18:[2,13]},{15:[1,41]},{15:[2,14]},{15:[2,15]},o($V6,[2,16]),o($Vb,[2,39]),o($Vb,[2,40]),o($V6,[2,17]),{28:[1,42],70:$V9,71:$Va},o($V6,[2,19]),{43:43,45:$Vc},{44:[1,44]},{46:[1,45]},o($V6,[2,11]),o($V6,[2,10]),{29:[1,46]},{44:[1,47]},o($Vd,[2,21]),{47:[1,48]},{30:[1,49]},o($Vd,[2,20]),{48:[1,50]},{31:[1,51]},{49:52,54:53,55:[1,54],56:[1,55]},{32:[1,56]},{50:[1,57]},{55:[1,58],56:[1,59]},{50:[2,24]},{45:[1,60]},{30:[1,61]},{51:62,59:63,60:[1,64],61:[1,65]},{50:[2,23]},{45:[1,66]},{46:[1,67]},{33:[1,68]},{52:[1,69]},{60:[1,70],61:[1,71]},{52:[2,30]},{45:[1,72]},{46:[1,73]},{47:[1,74]},{34:[1,75]},{53:76,64:77,65:[1,78],66:[1,79]},{52:[2,29]},{45:[1,80]},{46:[1,81]},{47:[1,82]},{32:$Ve,57:83},{22:85,70:$V7,71:$V8},{44:[2,22]},{65:[1,86],66:[1,87]},{44:[2,34]},{46:[1,88]},{46:[1,89]},{47:[1,90]},{32:$Ve,57:91},{32:$Vf,58:[1,92]},{46:[1,94]},{35:[1,95],70:$V9,71:$Va},{44:[2,33]},{46:[1,96]},{67:[1,97]},{47:[1,98]},{62:99,68:$Vg},{32:$Vf,58:[1,101]},o($Vh,[2,26]),{46:[1,102]},{33:[1,103]},{36:[1,104]},{67:[1,105]},o($Vi,[2,36]),{62:106,68:$Vg},{63:[1,107],68:$Vj},{46:[1,109]},o($Vh,[2,25]),{33:[1,110]},o($Vk,[2,28]),{22:111,70:$V7,71:$V8},o($Vi,[2,35]),{63:[1,112],68:$Vj},o($Vl,[2,32]),{46:[1,113]},{69:[1,114]},o($Vk,[2,27]),{37:[1,115],70:$V9,71:$Va},o($Vl,[2,31]),{69:[1,116]},o($Vm,[2,38]),{38:[1,117]},o($Vm,[2,37]),o($V6,[2,18])],
defaultActions: {16:[2,1],26:[2,12],27:[2,13],29:[2,14],30:[2,15],54:[2,24],58:[2,23],64:[2,30],70:[2,29],76:[2,22],78:[2,34],86:[2,33]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

    function TokenError(){
    	this.lexema = "";
    	this.descripcion = "";
    	this.fila = "";
    	this.columna = "";
    	this.tipo = "";
    }

    function AST_LUP(){
    	this.login = false;
    	this.logout = false;
    	this.contMess = 0;
    	this.contData = 0;
    	this.contErr = 0;
    	this.contDBMS = 0;
    	this.data = {};
    	this.errores = {};
	    this.mensajes = {};
	    this.dbms = {};
    }

    var ast = new AST_LUP();
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-insensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {


var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:this.begin("res_message"); return 21
break;
case 1:this.begin('INITIAL');  return 23;
break;
case 2:return 70
break;
case 3:return 71
break;
case 4:this.begin("res_lexema"); return 27
break;
case 5:this.begin('INITIAL');  return 28;
break;
case 6:return 70
break;
case 7:return 71
break;
case 8:this.begin("res_descripcion"); return 36
break;
case 9:this.begin('INITIAL');  return 37;
break;
case 10:return 70
break;
case 11:return 71
break;
case 12:this.begin("res_type"); return 34
break;
case 13:this.begin('INITIAL');  return 35;
break;
case 14:return 70
break;
case 15:return 71
break;
case 16:this.begin("res_data"); return 24
break;
case 17:this.begin('INITIAL');  return 25;
break;
case 18:return 70
break;
case 19:return 71
break;
case 20:/* skip whitespace */
break;
case 21:return 39;
break;
case 22:return 41;
break;
case 23:return 68;
break;
case 24:return 69;
break;
case 25:return 42;
break;
case 26:return 44;
break;
case 27:return 45;
break;
case 28:return 47;
break;
case 29:return 48;
break;
case 30:return 55;
break;
case 31:return 56;
break;
case 32:return 58;
break;
case 33:return 50;
break;
case 34:return 60;
break;
case 35:return 61;
break;
case 36:return 63;
break;
case 37:return 52;
break;
case 38:return 65;
break;
case 39:return 66;
break;
case 40:return 67;
break;
case 41:return 26;
break;
case 42:return 38;
break;
case 43:return 29;
break;
case 44:return 31;
break;
case 45:return 32;
break;
case 46:return 33;
break;
case 47:return 13;
break;
case 48:return 15;
break;
case 49:return 16;
break;
case 50:return 18;
break;
case 51:return 19;
break;
case 52:return 20;
break;
case 53:return 30;
break;
case 54:return 46;
break;
case 55:return 5;
break;
case 56: console.error('Este es un error léxico: ' + yy_.yytext + ', en la linea: ' + yy_.yylloc.first_line + ', en la columna: ' + yy_.yylloc.first_column); 
break;
}
},
rules: [/^(?:\[\+MESSAGE\])/i,/^(?:\[-MESSAGE\])/i,/^(?:.)/i,/^(?:[\t\r\n\f])/i,/^(?:\[\+LEXEMA\])/i,/^(?:\[-LEXEMA\])/i,/^(?:.)/i,/^(?:[\t\r\n\f])/i,/^(?:\[\+DESC\])/i,/^(?:\[-DESC\])/i,/^(?:.)/i,/^(?:[\t\r\n\f])/i,/^(?:\[\+TYPE\])/i,/^(?:\[-TYPE\])/i,/^(?:.)/i,/^(?:[\t\r\n\f])/i,/^(?:\[\+DATA\])/i,/^(?:\[-DATA\])/i,/^(?:.)/i,/^(?:[\t\r\n\f])/i,/^(?:\s+)/i,/^(?:\[\+DATABASES\])/i,/^(?:\[-DATABASES\])/i,/^(?:\[\+ATTRIBUTES\])/i,/^(?:\[-ATTRIBUTES\])/i,/^(?:\[\+DATABASE\])/i,/^(?:\[-DATABASE\])/i,/^(?:\[\+NAME\])/i,/^(?:\[-NAME\])/i,/^(?:\[\+TABLES\])/i,/^(?:\[-TABLES\])/i,/^(?:\[\+TABLE\])/i,/^(?:\[-TABLE\])/i,/^(?:\[\+TYPES\])/i,/^(?:\[-TYPES\])/i,/^(?:\[\+TYPECQL\])/i,/^(?:\[-TYPECQL\])/i,/^(?:\[\+PROCEDURES\])/i,/^(?:\[-PROCEDURES\])/i,/^(?:\[\+PROCEDURE\])/i,/^(?:\[-PROCEDURE\])/i,/^(?:\[\+ERROR\])/i,/^(?:\[-ERROR\])/i,/^(?:\[\+LINE\])/i,/^(?:\[-LINE\])/i,/^(?:\[\+COLUMN\])/i,/^(?:\[-COLUMN\])/i,/^(?:\[\+LOGIN\])/i,/^(?:\[-LOGIN\])/i,/^(?:\[\+LOGOUT\])/i,/^(?:\[-LOGOUT\])/i,/^(?:\[SUCCESS\])/i,/^(?:\[FAIL\])/i,/^(?:([0-9])+)/i,/^(?:(([A-Za-zÑñ])|_)(([A-Za-zÑñ])+|([0-9])*|_)*)/i,/^(?:$)/i,/^(?:.)/i],
conditions: {"res_data":{"rules":[0,4,8,12,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56],"inclusive":true},"res_type":{"rules":[0,4,8,12,13,14,15,16,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56],"inclusive":true},"res_descripcion":{"rules":[0,4,8,9,10,11,12,16,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56],"inclusive":true},"res_lexema":{"rules":[0,4,5,6,7,8,12,16,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56],"inclusive":true},"res_message":{"rules":[0,1,2,3,4,8,12,16,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56],"inclusive":true},"INITIAL":{"rules":[0,4,8,12,16,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = Analizador;
exports.Parser = Analizador.Parser;
exports.parse = function () { return Analizador.parse.apply(Analizador, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}