//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.RutasSoap")]
    public interface RutasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getErroresChisonResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getErroresChison", ReplyAction="*")]
        Cliente.localhost.getErroresChisonResponse getErroresChison(Cliente.localhost.getErroresChisonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getErroresChison", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente.localhost.getErroresChisonResponse> getErroresChisonAsync(Cliente.localhost.getErroresChisonRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cadena del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalizarLUP", ReplyAction="*")]
        Cliente.localhost.AnalizarLUPResponse AnalizarLUP(Cliente.localhost.AnalizarLUPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalizarLUP", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente.localhost.AnalizarLUPResponse> AnalizarLUPAsync(Cliente.localhost.AnalizarLUPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getErroresChisonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getErroresChison", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.localhost.getErroresChisonRequestBody Body;
        
        public getErroresChisonRequest() {
        }
        
        public getErroresChisonRequest(Cliente.localhost.getErroresChisonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getErroresChisonRequestBody {
        
        public getErroresChisonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getErroresChisonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getErroresChisonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.localhost.getErroresChisonResponseBody Body;
        
        public getErroresChisonResponse() {
        }
        
        public getErroresChisonResponse(Cliente.localhost.getErroresChisonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getErroresChisonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getErroresChisonResult;
        
        public getErroresChisonResponseBody() {
        }
        
        public getErroresChisonResponseBody(string getErroresChisonResult) {
            this.getErroresChisonResult = getErroresChisonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalizarLUPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalizarLUP", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.localhost.AnalizarLUPRequestBody Body;
        
        public AnalizarLUPRequest() {
        }
        
        public AnalizarLUPRequest(Cliente.localhost.AnalizarLUPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalizarLUPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cadena;
        
        public AnalizarLUPRequestBody() {
        }
        
        public AnalizarLUPRequestBody(string cadena) {
            this.cadena = cadena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalizarLUPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalizarLUPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.localhost.AnalizarLUPResponseBody Body;
        
        public AnalizarLUPResponse() {
        }
        
        public AnalizarLUPResponse(Cliente.localhost.AnalizarLUPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalizarLUPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnalizarLUPResult;
        
        public AnalizarLUPResponseBody() {
        }
        
        public AnalizarLUPResponseBody(string AnalizarLUPResult) {
            this.AnalizarLUPResult = AnalizarLUPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RutasSoapChannel : Cliente.localhost.RutasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RutasSoapClient : System.ServiceModel.ClientBase<Cliente.localhost.RutasSoap>, Cliente.localhost.RutasSoap {
        
        public RutasSoapClient() {
        }
        
        public RutasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RutasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RutasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RutasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.localhost.getErroresChisonResponse Cliente.localhost.RutasSoap.getErroresChison(Cliente.localhost.getErroresChisonRequest request) {
            return base.Channel.getErroresChison(request);
        }
        
        public string getErroresChison() {
            Cliente.localhost.getErroresChisonRequest inValue = new Cliente.localhost.getErroresChisonRequest();
            inValue.Body = new Cliente.localhost.getErroresChisonRequestBody();
            Cliente.localhost.getErroresChisonResponse retVal = ((Cliente.localhost.RutasSoap)(this)).getErroresChison(inValue);
            return retVal.Body.getErroresChisonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.localhost.getErroresChisonResponse> Cliente.localhost.RutasSoap.getErroresChisonAsync(Cliente.localhost.getErroresChisonRequest request) {
            return base.Channel.getErroresChisonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.localhost.getErroresChisonResponse> getErroresChisonAsync() {
            Cliente.localhost.getErroresChisonRequest inValue = new Cliente.localhost.getErroresChisonRequest();
            inValue.Body = new Cliente.localhost.getErroresChisonRequestBody();
            return ((Cliente.localhost.RutasSoap)(this)).getErroresChisonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.localhost.AnalizarLUPResponse Cliente.localhost.RutasSoap.AnalizarLUP(Cliente.localhost.AnalizarLUPRequest request) {
            return base.Channel.AnalizarLUP(request);
        }
        
        public string AnalizarLUP(string cadena) {
            Cliente.localhost.AnalizarLUPRequest inValue = new Cliente.localhost.AnalizarLUPRequest();
            inValue.Body = new Cliente.localhost.AnalizarLUPRequestBody();
            inValue.Body.cadena = cadena;
            Cliente.localhost.AnalizarLUPResponse retVal = ((Cliente.localhost.RutasSoap)(this)).AnalizarLUP(inValue);
            return retVal.Body.AnalizarLUPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.localhost.AnalizarLUPResponse> Cliente.localhost.RutasSoap.AnalizarLUPAsync(Cliente.localhost.AnalizarLUPRequest request) {
            return base.Channel.AnalizarLUPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.localhost.AnalizarLUPResponse> AnalizarLUPAsync(string cadena) {
            Cliente.localhost.AnalizarLUPRequest inValue = new Cliente.localhost.AnalizarLUPRequest();
            inValue.Body = new Cliente.localhost.AnalizarLUPRequestBody();
            inValue.Body.cadena = cadena;
            return ((Cliente.localhost.RutasSoap)(this)).AnalizarLUPAsync(inValue);
        }
    }
}
